-- ═══════════════════════════════════════════════════════════════════
-- Shorts Maker projects and their Shorts (Movievideomaker's shortsbot/web.py,
-- web_store.SupabaseStore). Found once per YouTube link: each Short's title,
-- description, viral score and where it's cut. The rendered video files stay
-- on the render server and are deleted after a while; this metadata stays, so
-- a project always opens as it was and a Short renders again on download.
--
-- Written only by the render server (service role). A signed-in user can read
-- their OWN projects and Shorts straight from here, so the Shorts page opens
-- instantly without waiting on the render server.
-- Times are unix seconds (double precision), as the server keeps them.
-- ═══════════════════════════════════════════════════════════════════
create table if not exists public.shorts_projects (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  url          text not null,
  video_id     text,
  title        text,
  thumb        text,
  duration     double precision,
  length       text,
  subtitles    text,
  style        text,
  instructions text,
  options      text,               -- the Studio picks, as JSON
  status       text not null,
  error        text,
  created_at   double precision not null
);
create index if not exists shorts_projects_user_idx on public.shorts_projects(user_id, created_at desc);
create index if not exists shorts_projects_status_idx on public.shorts_projects(status);

create table if not exists public.shorts_clips (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.shorts_projects(id) on delete cascade,
  idx         integer not null,
  start_sec   double precision not null,
  end_sec     double precision not null,
  orig_start  double precision not null,
  orig_end    double precision not null,
  title       text,
  title_lines jsonb not null default '[]'::jsonb,
  description text,
  score       integer,
  reason      text,
  speaker     text,
  status      text not null default 'idle',
  stage       text,
  file        text,
  file_start  double precision,
  file_end    double precision,
  rendered_at double precision,
  charged     boolean not null default false,
  renders     integer not null default 0,
  error       text,
  job_id      integer
);
create index if not exists shorts_clips_project_idx on public.shorts_clips(project_id, idx);
create index if not exists shorts_clips_status_idx on public.shorts_clips(status);

alter table public.shorts_projects enable row level security;
alter table public.shorts_clips enable row level security;

drop policy if exists "read own shorts projects" on public.shorts_projects;
create policy "read own shorts projects" on public.shorts_projects
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "read own shorts clips" on public.shorts_clips;
create policy "read own shorts clips" on public.shorts_clips
  for select to authenticated using (
    exists (select 1 from public.shorts_projects p where p.id = shorts_clips.project_id and p.user_id = (select auth.uid()))
  );
